spring:
  profiles:
    active: ${PROFILE_ACTIVE:default}
  application:
    name: payment-ms
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${vcap.services.keycloak.credentials.issuer-uri}
      client:
        provider:
          keycloak:
            issuer-uri: ${vcap.services.keycloak.credentials.issuer-uri}